apiVersion: v2
name: l2l
description: A meta chart for the deployment of Learning 2 Learn team
type: application
version: 0.1.0

dependencies:
  # NOTE: I've opted to avoid nesting JupyterHub / Dask Gateway under DaskHub
  #       but instead extract the configuration that DaskHub comes with in 
  #
  # # DaskHub (JupyterHub + Dask-Gateway with a little configuration)
  # - name: daskhub
  #   version: 4.5.4
  #   repository: https://helm.dask.org

  # JupyterHub
  # https://github.com/jupyterhub/zero-to-jupyterhub-k8s/jupyterhub
  - name: jupyterhub
    version: 0.10.2
    repository: https://jupyterhub.github.io/helm-chart/

  # Dask Gateway
  # https://github.com/dask/dask-gateway/tree/master/resources/helm/dask-gateway
  - name: dask-gateway
    version: 0.9.0
    repository: https://dask.org/dask-gateway-helm-repo/

  # Prometheus for collection of metrics.
  # https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus
  - name: prometheus
    version: 11.16.8
    repository: https://prometheus-community.github.io/helm-charts
    tags:
      - metrics

  # Grafana for dashboarding of metrics.
  # https://github.com/grafana/helm-charts/tree/main/charts/grafana
  - name: grafana
    version: 6.1.4
    repository: https://grafana.github.io/helm-charts
    tags:
      - metrics
