apiVersion: v2
name: l2l
description: A meta chart for the deployment of Learning 2 Learn team
type: application
version: 0.1.0

dependencies:
  # DaskHub (JupyterHub + Dask-Gateway with a little configuration in hub.extraConfig)
  # https://github.com/dask/helm-chart/tree/main/daskhub
  - name: daskhub
    # NOTE: If you upgrade daskhub, check the version of jupyterhub and
    #       dask-gateway you will upgrade from and to by inspecting the state of
    #       the daskhub Chart.yaml file before and after. For example if you
    #       upgrade from daskhub version 2021.7.2 to 2022.6.0, check the
    #       jupyterhub/dask-gateway versions declared in these two Chart.yaml
    #       files:
    #
    #       - https://github.com/dask/helm-chart/blob/2021.7.2/daskhub/Chart.yaml
    #       - https://github.com/dask/helm-chart/blob/2022.6.0/daskhub/Chart.yaml
    #
    #       In this case, we can see that upgrading from daskhub 2021.7.2 to
    #       2022.6.1 leads to bumping jupyterhub from 1.1.1 to 1.2.0, and
    #       dask-gateway from 0.9.0 to 2022.6.1.
    #
    #       With this information, inspect the changelogs for these helm charts
    #       and follow possible upgrade procedures if needed before making the
    #       upgrade:
    #
    #       - Changelog for jupyterhub Helm chart: https://z2jh.jupyter.org/en/latest/changelog.html
    #       - Changelog for dask-gateway Helm chart: https://gateway.dask.org/changelog.html
    #
    version: 2021.7.2  # https://github.com/dask/helm-chart/blob/2021.7.2/daskhub/Chart.yaml
    repository: https://helm.dask.org

  # # JupyterHub
  # # https://github.com/jupyterhub/zero-to-jupyterhub-k8s/jupyterhub
  # - name: jupyterhub
  #   version: 1.1.1
  #   repository: https://jupyterhub.github.io/helm-chart/

  # # Dask Gateway
  # # https://github.com/dask/dask-gateway/tree/main/resources/helm/dask-gateway
  # - name: dask-gateway
  #   version: 0.9.0
  #   repository: https://dask.org/dask-gateway-helm-repo/
  #   tags:
  #     - dask-gateway

  # Prometheus for collection of metrics.
  # https://github.com/prometheus-community/helm-charts/tree/main/charts/prometheus
  - name: prometheus
    version: 14.4.1
    repository: https://prometheus-community.github.io/helm-charts
    tags:
      - metrics

  # Grafana for dashboarding of metrics.
  # https://github.com/grafana/helm-charts/tree/main/charts/grafana
  - name: grafana
    version: 6.14.1
    repository: https://grafana.github.io/helm-charts
    tags:
      - metrics
