jupyterhub:
    hub:
        cookieSecret: ENC[AES256_GCM,data:y7q2F1Ezqku2cqHutxe8+rzQqFAZHAwO9JM7v8KOtRvPyySq0Si2hoNxS4BZa5HydYKMGfVZJniNr44oi26jew==,iv:I6O0dNgKVajl3QW45bIqlehbdhr2NGk9jX1w9KxNzuk=,tag:/N8T4hNMP8flbiuEdIduOQ==,type:str]
        services:
            dask-gateway:
                apiToken: ENC[AES256_GCM,data:VKzvkAsOH90KD7OxFRul4PYbaXMum5B4j0QSQWwoa5L/HFjwgutvi6SaBQMINSWtQ9SUaGE+hV5ffe9ft5AvEg==,iv:2ajVleU5Px8UYm6l0CtyzRUUZe3/uVwKA3lThVq+2B4=,tag:fx+bTPwuqiYBk3skIo8uuQ==,type:str]
    proxy:
        https:
            letsencrypt:
                contactEmail: ENC[AES256_GCM,data:wPWh8o340WLfkap0ehIVYsRLtbDq8izoxQ==,iv:7TOizMNnXudzz7QiBkB8vjwvPi5w1gkixJCH5RYjK+A=,tag:NfPSgGbe+nSQtEsMBUdQYA==,type:str]
        secretToken: ENC[AES256_GCM,data:jxtILgJHZH0qV3IPTTaWHjNuzR7YmXPLOEiHnQ1xQ+aPNT8pot8YWQY3jUwzQPL9f5CTjQlq9at86g3pxOIDnw==,iv:edwTHjq/5y7ncwPTNMmZHAaj89JdRtuEl+kPS97EI20=,tag:EXHHrqzBDZ+geDe2IiFaYQ==,type:str]
    auth:
        github:
            clientId: ENC[AES256_GCM,data:3zhGl6UW/sXkiNTs/RLW+dmu7zI=,iv:hKtw7XZqbUZvpjEb3Ag9Cgox0PtP/LCWun3yBqXnRq4=,tag:sDGaKj667NO3wZ4uoJq6Sg==,type:str]
            clientSecret: ENC[AES256_GCM,data:2XfJx2TSbSsXF7Zfj7RHwjsf5oVwJh36hCdLNNDb2FySeNJr6O2Vkw==,iv:5gW1nEBRkV/eE4WA/rB6RRFMX1yxzlF+E3xJxSiKvR0=,tag:k+kquz1OVWeWDnHkR0015Q==,type:str]
dask-gateway:
    gateway:
        auth:
            jupyterhub:
                apiToken: ENC[AES256_GCM,data:Gr4vSXv6NXp7oqezhXumyg9seFclz/Bj1yC3OHY6N2t5sK0wVA236+Q3FumbbHzsGPOqzNJmwLsvh3mwdCp04Q==,iv:52x6oeUXVtDrlNx1OzdPnA+OynvARQTVaKhxuFXXTro=,tag:/OxTKCBky1p8YgTj+H/XHQ==,type:str]
grafana:
    adminPassword: ENC[AES256_GCM,data:GLK6BSUYhOupnlws1FPsBDTq,iv:Rg93Kb3t5hpk4xsVoR+39/OWbXQ/x+I3g/sEx/e/QEg=,tag:bwAB0kUL25totaeGRe4M8g==,type:str]
    grafana.ini:
        security:
            secret_key: ENC[AES256_GCM,data:kYtnJtSy03C6FxKiWwDShuRJk2dDxiKFiGmxX1HcCGb2o6onwTy/gnjzb55PpRhZj3q6NSyo1g5/vtZJ+t5MFw==,iv:2Seb+yP1zVj1tP6l02roopDTjmW3Iwwgm8EnoSCD4hc=,tag:seYwgFZe4LKdtwHJ+8hkfw==,type:str]
sops:
    kms:
    -   arn: arn:aws:kms:us-west-2:423786577274:key/80fbf43c-a522-4625-ac6d-e6482ddb97e4
        created_at: '2020-11-18T06:11:11Z'
        enc: AQICAHh8Itoe2XmQGnwWilS2yiI0I2S8x32ONfaMDv3COF3yvwFM/hxKWPdFFom5d46XAM9AAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMlvx+S/m/NqYTOiqVAgEQgDsXSUoWtzYXk7VTGZSWwTP8irxACLYiWtVIrXr1x6ZgjWWOPQlbGXWqu4d7j41NrUrivQ56KJu8vPz4kw==
        aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    lastmodified: '2020-11-21T01:38:35Z'
    mac: ENC[AES256_GCM,data:hyvWpxsvyx6Mfc6P/sJIZbz5r5IWSbXGAW9ntWENk10T+z1BFv9zkuDvCKk5SP44ECh0G3RyvkaMzkQpU+py6DfkxNsyEKZ9Sv3DBRD4OZFLz+P/A/ju4hPbSly6b3Fsv/+8PR5mYfl9d9vgm3S98/2ATeTdZa5iGcx+UWao3v4=,iv:C8HukT2gtkS3fNIviTFGUWpg2zldiQIEgsqEodZWhHM=,tag:hXfF+5yeaFnz6HftFC3PJQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.6.1
