{{- if .Values.nfs.enabled -}}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: {{ .Values.nfs.serverIP | quote }}
    path: "/{{ .Values.nfs.serverName }}"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
spec:
  accessModes:
    - ReadWriteMany
  volumeName: nfs-pv
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
{{- end }}
