apiVersion: v1
kind: ConfigMap
metadata:
  name: user-etc-singleuser
data:
  {{- (.Files.Glob "files/etc/singleuser/*").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-etc-profile-d
data:
  {{- (.Files.Glob "files/etc/profile.d/*").AsConfig | nindent 2 }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-usr-local-etc-jupyter
data:
  {{- (.Files.Glob "files/usr/local/etc/jupyter/*").AsConfig | nindent 2 }}
