name: user-env
channels:
  - conda-forge
dependencies:
  - bqplot=0.12.16
  - cython
  - datashader==0.7.0
  - gcsfs==0.6.2
  - google-cloud-sdk
  - hdf5>=1.10.5
  - holoviews
  - hvplot
  - intake
  - ipywidgets
  - line_profiler
  - matplotlib==3.1.0
  - mne==0.18.2
  - nitime==0.7
  - numba==0.43.1
  - oct2py==5.0.2
  - octave_kernel
  - panel
  - pip
  - plotly==4.9.0
  - prefect==0.6.3
  - scikit-image==0.15.0
  - seaborn==0.9.0
  - tqdm==4.32.1
  - xarray==0.14.1
  - zarr==2.3.1
  - pip:
    - bycycle==0.1.2
    - dask[complete]
        # Client side usage of dask.
        # ref: https://docs.dask.org/en/latest/install.html
    - dask-gateway==0.9.0
        # Client side management of distributed resources, pinned to
        # dask-gateway helm chart version.
        # ref: https://gateway.dask.org/install-user.html
    - dask_labextension
        # A prerequisite for the JupyterLab extension dask-labextension, which
        # also needs to be enabled as a serverextension.
        # ref: https://github.com/dask/dask-labextension
    - dpca
    - fooof==0.1.3
    - git+https://github.com/ahwillia/tensortools@v0.3.0
    - git+https://github.com/neurodsp-tools/neurodsp@ed82caa2d93606d1500de0997dce962b81bc69eb
    - nbgitpuller
        # allows us to use links like ...com/user/user-redirect/git-pull?repo=...
    - nbresuse
        # combined with the status bar plugin, allows us to see memory usage
    - nwbwidgets
    - pactools
