name: deploy-aws

# Only run this when the chosen branch's chart/deployments folder changes
on:
  push:
    paths: ["chart/**", "deployments/**"]
    branches: ["aws-2020"]

# This job:
# - Installs the CLIs: aws, sops, and hubploy
# - Relies on GitHub secrets AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY for
#   access to a AWS account created with infra/cloudformation-hubploy.yaml
# - Use hubploy to build an image with repo2docker
# - Use hubploy to deploy the Helm chart in ./chart to EKS
# - Annotates a Grafana dashboard that a deployment started
jobs:
  deploy-aws:
    name: Deploy Helm chart
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        # Required for hubploy's use of chartpress that inspects git history
        fetch-depth: 0
    - uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install aws, sops, and hubploy CLIs
      run: |
        # sops
        curl -sSL https://github.com/mozilla/sops/releases/download/v3.6.1/sops_3.6.1_amd64.deb -o /tmp/sops.deb
        sudo apt-get install /tmp/sops.deb

        # aws
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update

        # hubploy
        pip install https://github.com/yuvipanda/hubploy/archive/master.zip

    - name: "hubploy: build"
      id: hubploy_build
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        hubploy build l2l --push

    - name: Push a Grafana dashboard annotation
      uses: frankie567/grafana-annotation-action@v1.0.3
      continue-on-error: true
      with:
        apiHost: https://l2l.sundellopensource.com/services/grafana
        apiToken: ${{ secrets.GRAFANA_API_TOKEN }}
        text: |
          Deployment triggered by ${{ github.actor }}.
          - <a href="${{ github.event.repository.html_url }}/actions/runs/${{ github.run_id }}">Inspect CI run</a>
          - <a href="${{ github.event.repository.html_url }}/compare/${{ github.event.before }}..${{ github.event.after }}">Compare commits</a>
        tags: deployment,github

    - name: "hubploy: deploy"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: |
        hubploy deploy --namespace default --cleanup-on-fail l2l ./chart prod
