name: user-env
channels:
  - conda-forge
dependencies:
  - pangeo-notebook
  - bqplot=0.12.16
  - cython
  - datashader==0.7.0
  - google-cloud-sdk
  - holoviews
  - line_profiler
  - mne==0.18.2
  - nitime==0.7
  - oct2py==5.0.2
  - octave_kernel
  - plotly==4.9.0
  - seaborn==0.9.0
  - pip:
    - bycycle==0.1.2
    - dpca
    - fooof==0.1.3
    - julia
    - git+https://github.com/ahwillia/tensortools@v0.3.0
    - git+https://github.com/neurodsp-tools/neurodsp@ed82caa2d93606d1500de0997dce962b81bc69eb
    - nbresuse
        # combined with the status bar plugin, allows us to see memory usage
    - nwbwidgets
    - pactools
